Bash rewrite
Everything has been rewritten to bash, and with a strict style guide.

Some of the new motivations and guidelines can be found in the README.
Beyond what is specified there:

 + bash arrays solve so many problems
 + bash variable expansions solve the few problems that bash arrays
   can't solve
 + bash read is a god-send
 + thanks to bash read, I have a nearly fully functional argument parser
   + still need to obey -- but that's a problem for future me
 + given how this codebase has grown, I have a decent usecase for a
   single, well-tested library of functions
 + I no longer care about portability, I care about deploy-ability. Who
   cares if my scripts can't be used in a server with only a POSIX shell
   implementation? It's trivial to install bash anywhere. For the same
   reason, I am seriously looking at rewriting more scripts into either
   Go or Raku.

diff --git a/archives/mktar b/archives/mktar
--- a/archives/mktar
+++ b/archives/mktar
@@ -1,153 +1,229 @@
-#!/bin/bash
+#! /bin/bash
 
 name="mktar"
-version="1.4"
+version="2.0"
 read -r -d '' help_message <<-EOF
-	Archive utility
-	Usage: mktar -n OUTFILE [OPTIONS] INFILES
+	Make an archive
+	Usage: mktar --name=OUTFILE [OPTIONS] FILE..
 	Options:
-	 --checksum=ALGO               create checksum with [none|sha1|sha256]
-	 -d DIR, --from-directory DIR  archive from a directory
-	 -h, --help                    print this message
-	 -n FILE, --name FILE          name of archive
-	 -p PASS, --passphrase PASS    passphrase for encryption
-	 -q, --quiet                   suppress error messages and prompts
-	 -v, --verbose                 show additional messages
-	 -V, --version                 print version number and exit
+	 --checksum=ALGO             create checksum with [none|sha1|sha256|sha512]
+	 -d=DIR,                     working directory
+	   --from-directory=DIR,
+	   --working-directory=DIR
+	 -h, --help                  print this message
+	 -n=FILE, --name=FILE        name of archive
+	 -p=PASS, --passphrase=PASS  use plaintext passphrase
+	 -q, --quiet                 suppress error messages and prompts
+	 -v, --verbose               show additional messages
+	 -V, --version               print version number and exit
 EOF
 
-source /usr/local/lib/mylib.bash
-source /usr/local/lib/archive.bash
+. /usr/local/lib/mylib.bash
+. /usr/local/lib/myarchivelib.bash
 
-archive_fn=""
-checksum=-1
-from_directory=""
 positional=()
+archive_fn=""
+checksum="none"
+passwd=""
 quiet=0
 verbose=0
-while [[ $# -gt 0 ]]; do
-  case $1 in
+working_directory="."
 
-  --checksum=no|--checksum=none|--checksum=0)
-    debug_msg "Setting checksum option to 0 (=none) (was ${checksum})"
-    checksum=0
-    shift
-    ;;
-
-  --checksum=sha1|--checksum=1)
-    debug_msg "Setting checksum option to 1 (=sha1) (was ${checksum})"
-    checksum=1
-    shift
-    ;;
-
-  --checksum=sha256|--checksum=2)
-    debug_msg "Setting checksum option to 2 (=sha256) (was ${checksum})"
-    checksum=2
-    shift
-    ;;
+while [[ "${#}" -gt 0 ]]; do
+  case "${1}" in
 
   --checksum=*)
-    attempted_checksum="$(/usr/bin/printf "%s\n" "$1" | sed -e 's/^.*=//' )"
-    error_msg "Unknown checksum '${attempted_checksum}'"
+    IFS='=' read -r flag extract <<<"${1}"
+    new="$(ParseChecksumArgument "${extract}")"
+    if [[ -z "${new}" ]]; then
+      Error "parser: cannot use checksum algorithm '${new}'"
+    else
+      Debug "parser: --checksum='${new}' (was ${checksum})"
+      checksum="${new}"
+    fi
+    shift
     ;;
 
-  -d|--from-directory)
-    debug_msg "Setting from_directory option to '${2}' (was ${from_directory})"
-    from_directory="--directory $2"
+  --checksum)
+    new="$(ParseChecksumArgument "${2}")"
+    if [[ -z "${new}" ]]; then
+      Error "parser: cannot use checksum algorithm '${new}'"
+    else
+      Debug "parser: --checksum='${new}' (was ${checksum})"
+      checksum="${new}"
+    fi
+    shift; shift
+    ;;
+
+  -d=*|--from-directory=*|--working-directory=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    Debug "parser: --working-directory='${extract}' (was ${working_directory})"
+    working_directory="${extract}"
+    shift
+    ;;
+
+  -d|--from-directory|--working-directory)
+    Debug "parser: --working-directory='${2}' (was ${working_directory})"
+    working_directory="${2}"
     shift; shift
     ;;
 
   -h|--help)
-    help_msg
+    Help
+    shift
+    ;;
+
+  -n=*|--name=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    Debug "parser: --name='${extract}' (was ${archive_fn})"
+    archive_fn="${extract}"
     shift
     ;;
 
   -n|--name)
-    debug_msg "Setting output filename to ${2} (was ${archive_fn})"
-    archive_fn="$2"
+    Debug "parser: --name='${2}' (was ${archive_fn})"
+    archive_fn="${2}"
     shift; shift
     ;;
 
-  -p|--passphrase)
-    debug_msg "Setting passphrase to ${2} (was ${passphrase})"
-    passphrase="--passphrase $2"
+  -p=*|--passwd=*|--passphrase=*)
+    #NOTE: Normally would emit a message with Debug, but that seems like a bad
+    #      idea here.
+    IFS='=' read -r flag extract <<<"${1}"
+    passwd="${extract}"
+    shift
+    ;;
+
+  -p|--passwd|--passphrase)
+    #NOTE: Normally would emit a message with Debug, but that seems like a bad
+    #      idea here.
+    passwd="${2}"
     shift; shift
     ;;
 
   -q|--quiet)
-    debug_msg "Setting quiet option to 1 (was ${quiet})"
+    #NOTE: Normally would emit a message with Debug, but the user is
+    #      specifically requesting that we do not.
     quiet=1
     shift
     ;;
 
   -v|--verbose)
-    debug_msg "Setting verbose option to 1 (was ${verbose})"
+    Debug "parser: --verbose=1 (was ${verbose})"
     verbose=1
     shift
     ;;
 
   -V|--version)
-    version_msg
+    Version
     ;;
 
   *)
-    debug_msg "Argument '${1}' added to positional array"
+    Debug "parser: '${1}' appended to positional arguments"
     positional+=("$1")
     shift
     ;;
   esac
 done
 
-# error if no archive file given
-if [[ -z "$archive_fn" ]]; then
-  error_msg "no archive file given"
-  usage_msg
+RequirePositionalArguments
+
+
+# Part 1: Handle archive file.
+if [[ -z "${archive_fn}" ]]; then
+  Usage
 fi
 
-# determine archive action
-archive_action="$(archive_extension "$archive_fn" | tee >(>&2 /usr/bin/head -n -1) | /usr/bin/tail -n 1)"
-
-# determine checksum action and filename
-if [[ "$checksum" -eq 1 ]]; then
-  checksum_action="sha1"
-elif [[ "$checksum" -eq 2 ]]; then
-  checksum_action="sha256"
-fi
-checksum_fn="$(fn_basename "$archive_fn").${checksum_action}"
-
-# check checksum files
-if [[ "$checksum" -ge 1 ]]; then
-  if contains "$checksum_fn" "${positional[@]}"; then
-    error_msg "checksum '${checksum_fn}' cannot be an input file"
-  elif ! prompt_overwrite "checksum_fn"; then
-    error_msg "checksum '${checksum_fn}' cannot be overwritten"
-  fi
-fi
-
-# check passphrase
-if [[ "$encrypt" -ge 1 && -z "$passphrase" ]]; then
-  passphrase=
-fi
-
-if ! archive --archive=$archive_action --name "$archive_fn" $passphrase $from_directory "${positional[@]}"; then
+archive_path="$(FileAbsolute "${archive_fn}")"
+if [[ -z "${archive_path}" ]]; then
   exit 1
 fi
 
-code=0
-if [[ "$checksum" -ge 1 ]]; then
-  case "$checksum_action" in
-  sha1)
-    if ! /usr/bin/sha1sum "$archive_fn" | /usr/bin/awk '{print $1}' > "$checksum_fn"; then
-      code=1
-    fi
-    ;;
+if ! SupportedArchive "${archive_fn}"; then
+  Fatal "file '${archive_fn}' is not a supported archive"
 
-  sha256)
-    if ! /usr/bin/sha256sum "$archive_fn" | /usr/bin/awk '{print $1}' > "$checksum_fn"; then
-      code=1
+elif [[ -e "${archive_path}" ]]; then
+
+  #NOTE: Not really an issue if we overwrite, but this mistake happens often
+  #      enough (to me) that I want this bubblewrap built in.
+  if ArrayContains "${checksum_fn}" "${positional[@]}"; then
+    Fatal "file '${archive_fn}' is both an input and output"
+
+  elif ! PromptOverwrite "${archive_fn}"; then
+    exit 1
+  fi
+
+
+  if ! /usr/bin/rm "${archive_path}"; then
+    Fatal "failed to overwrite file '${archive_fn}'"
+
+  fi
+fi
+
+
+# Part 2: Handle working directory.
+if [[ ! -d "${working_directory}" ]]; then
+  Fatal "no such directory '${working_directory}'"
+fi
+
+path="$(FileAbsolute "${working_directory}")"
+if [[ -z "${path}" ]]; then
+  exit 1
+fi
+
+#NOTE: Directory already validated, so who knows why this would fail? Just
+#      report it to the user.
+if ! cd "${path}"; then
+  Fatal "failed to enter directory '${working_directory}'"
+fi
+
+if [[ -z "${archive_fn}" ]]; then
+  Usage
+fi
+
+
+# Part 3: Interpret checksum request.
+if [[ "${checksum}" != "none" ]]; then
+  checksum_fn="$(FileBasename "${archive_fn}").${checksum}"
+
+  checksum_path="$(FileAbsolute "${checksum_fn}")"
+  if [[ -z "${checksum_path}" ]]; then
+    exit 1
+  fi
+
+  if [[ -e "${checksum_path}" ]]; then
+    if ArrayContains "${checksum_fn}" "${positional[@]}"; then
+      Fatal "file '${checksum_fn}' is both an input and output"
+    elif ! PromptOverwrite "${checksum_fn}"; then
+      exit 1
     fi
-    ;;
-  esac
+
+    if ! /usr/bin/rm "${checksum_path}"; then
+      Fatal "failed to overwrite file '${checksum_fn}'"
+    fi
+  fi
+fi
+
+
+# Part 4: Make archive.
+code=0
+
+if [[ -z "${passwd}" ]]; then
+  if ! MkArchive "${archive_fn}" "${positional[@]}"; then
+    code=1
+  fi
+
+else
+  if ! MkArchivePlaintext "${passwd}" "${archive_fn}" "${positional[@]}"; then
+    code=1
+  fi
+
+fi
+
+if [[ "${code}" -eq 0 ]] && [[ "${checksum}" != "none" ]]; then
+  if ! MkSha "${checksum}" "${archive_fn}" "${checksum_fn}"; then
+    code=1
+  fi
 fi
 
 exit "$code"
diff --git a/archives/untar b/archives/untar
--- a/archives/untar
+++ b/archives/untar
@@ -1,78 +1,148 @@
 #!/bin/bash
 
 name="untar"
-version="1.2"
+version="1.3"
 help_message=$(/usr/bin/cat <<-EOF
-	Unarchive utility
-	Usage: untar TARGET [..] [OPTIONS]
+	Extract files from an archive
+	Usage: untar [OPTIONS] FILE..
 	Options:
 	 -h, --help                  print this message and exit
-	 -d DIR, --to-directory DIR  unarchive to a directory
-	 -p PASS, --passphrase PASS  passphrase for decryption
+	 -d=DIR,                     working directory
+	   --from-directory=DIR,
+	   --working-directory=DIR
+	 -p PASS, --passphrase PASS  use plaintext passphrase
 	 -q, --quiet                 suppress error messages
 	 -v, --version               print version number and exit
 EOF
 )
 
-source /usr/local/lib/mylib.bash
-source /usr/local/lib/unarchive.bash
+. /usr/local/lib/mylib.bash
+. /usr/local/lib/myarchivelib.bash
 
-quiet=0
-passphrase=""
 positional=()
-to_directory=""
+passwd=""
+quiet=0
 verbose=0
-while [[ $# -gt 0 ]]; do
-  case $1 in
+working_directory="."
 
-  -d|--to-directory)
-    debug_msg "Setting to_directory option to '${2}' (was ${to_directory})"
-    to_directory="$2"
+while [[ "${#}" -gt 0 ]]; do
+  case "${1}" in
+
+  -d=*|--to-directory=*|--working-directory=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    Debug "parser: --working-directory='${extract}' (was ${working_directory})"
+    working_directory="${extract}"
+    shift
+    ;;
+
+  -d|--to-directory|--working-directory)
+    Debug "parser: --working-directory='${2}' (was ${working_directory})"
+    working_directory="${2}"
     shift; shift
     ;;
 
   -h|--help)
-    help_msg
+    Help
     shift
     ;;
 
+  -p=*|--passwd=*|--passphrase=*)
+    #NOTE: Normally would emit a message with Debug, but that seems like a bad
+    #      idea here.
+    IFS='=' read -r flag extract <<<"${1}"
+    passwd="${extract}"
+    shift
+    ;;
+
+  -p|--passwd|--passphrase)
+    #NOTE: Normally would emit a message with Debug, but that seems like a bad
+    #      idea here.
+    passwd="${2}"
+    shift; shift
+    ;;
+
   -q|--quiet)
-    debug_msg "Setting quiet option to 1 (was ${quiet})"
+    #NOTE: Normally would emit a message with Debug, but the user is
+    #      specifically requesting that we do not.
     quiet=1
     shift
     ;;
 
-  -p|--passphrase)
-    debug_msg "Setting passphrase option to '${2}' (was ${passphrase})"
-    passphrase="$2"
-    shift; shift
-    ;;
-
   -v|--verbose)
-    debug_msg "Setting verbose option to 1 (was ${verbose})"
+    Debug "parser: --verbose=1 (was ${verbose})"
     verbose=1
     shift
     ;;
 
   -V|--version)
-    version_msg
+    Version
     ;;
 
   *)
-    debug_msg "Argument '${1}' added to positional array"
+    Debug "parser: '${1}' appended to positional arguments"
     positional+=("$1")
     shift
     ;;
   esac
 done
 
-code=0
+RequirePositionalArguments
+
+
+# Part 1: Handle archive files.
+archive_fns=()
+
 for archive_fn in "${positional[@]}"; do
-  archive_action="$(archive_extension "$archive_fn" | tee >(>&2 /usr/bin/head -n -1) | /usr/bin/tail -n 1)"
-  if ! unarchive --archive=$archive_action "$archive_fn" ${passphrase:+--passphrase "$passphrase"} ${to_directory:+--directory "$to_directory"}; then
-    code=1
+  if [[ ! -e "${archive_fn}" ]]; then
+    Fatal "no such file '${archive_fn}'"
+  fi
+
+  archive_path="$(FileAbsolute "${archive_fn}")"
+  if [[ -z "${archive_path}" ]]; then
+    exit 1
+  fi
+
+  if ! SupportedArchive "${archive_fn}"; then
+    Fatal "file '${archive_fn}' is not a supported archive"
+  fi
+
+  archive_fns+=("${archive_path}")
+
+done
+
+
+# Part 2: Handle working directory.
+if [[ ! -d "${working_directory}" ]]; then
+  Fatal "no such directory '${working_directory}'"
+fi
+
+path="$(FileAbsolute "${working_directory}")"
+if [[ -z "${path}" ]]; then
+  exit 1
+fi
+
+#NOTE: Directory already validated, so who knows why this would fail? Just
+#      report it to the user.
+if ! cd "${path}"; then
+  Fatal "failed to enter directory '${working_directory}'"
+fi
+
+
+# Part 3: Extract files from archives.
+code=0
+
+for archive_fn in "${archive_fns[@]}"; do
+
+  if [[ -z "${passwd}" ]]; then
+    if ! ExtractArchive "${archive_fn}"; then
+      code=1
+    fi
+  else
+    if ! ExtractArchivePlaintext "${passwd}" "${archive_fn}"; then
+      code=1
+    fi
   fi
 done
 
-exit "$code"
+exit "${code}"
 
diff --git a/core/enumerate b/core/enumerate
--- a/core/enumerate
+++ b/core/enumerate
@@ -1,20 +1,20 @@
 #!/bin/bash
 
 name="enumerate"
-version="1.0"
+version="1.1"
 read -r -d '' help_message <<-EOF
-	Rename files in current directory into sequential numbers
-	Usage: enumerate [OPTIONS]
+	Rename files in a target directory (or current directory) sequentially
+	Usage: enumerate [OPTIONS] [TARGET]
 	Options:
 	 -d, --dry-run     print, not execute, changes (Default)
-	 -f P, --filter P  filter targets with filename pattern P
+	 -f=P, --filter=P  filter targets with filename pattern P
 	 -h, --help        print this message and exit
 	 -q, --quiet       suppress error messages
-	 -s N, --start N   start enumeration at N (Default: 1)
-	 -S N, --step N    step enumeration by N (Default: 1)
+	 -s=N, --start=N   start enumeration at N (Default: 1)
+	 -S=N, --step=N    step enumeration by N (Default: 1)
 	 -v, --verbose     show additional messages
 	 -V, --version     print version number and exit
-	 -w N, --width N   rename files to numbers N wide (Default: 4)
+	 -w=N, --width=N   rename files to numbers N wide (Default: 4)
 	 -x, --execute     execute changes
 EOF
 
@@ -29,99 +29,160 @@ width=4
 quiet=0
 verbose=0
 
-while [[ $# -gt 0 ]]; do
-  case $1 in
+while [[ "${#}" -gt 0 ]]; do
+  case "${1}" in
+
+  -f=*|--filter=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    Debug "parser: --filter='${extract}' (was ${filter})"
+    filter="${extract}"
+    shift
+    ;;
 
   -f|--filter)
-    debug_msg "Setting filter option to ${2} (was ${filter})"
-    filter="$2"
+    Debug "parser: --filter='${2}' (was ${filter})"
+    filter="${2}"
     shift; shift
     ;;
 
   -h|--help)
-    help_msg
+    Help
     shift
     ;;
 
   -q|--quiet)
-    debug_msg "Setting quiet option to 1 (was ${quiet})"
+    #NOTE: Normally would emit a message with Debug, but the user is
+    #      specifically requesting that we do not.
     quiet=1
     shift
     ;;
 
-  -s|--start)
-    if ! is_natural "$2"; then
-      error_msg "Cannot set enumeration start to '${2}' (not an integer >= 0)"
+  -s=*|--start=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    if ! IsNatural "${extract}"; then
+      Error "parser: cannot start at '${extract}' (not an integer >= 0)"
+    else
+      Debug "parser: --start=${extract} (was ${enum_start})"
+      enum_start="${extract}"
     fi
-    debug_msg "Setting enumeration start to ${2} (was ${enum_start})"
-    enum_start="$2"
+    shift
+    ;;
+
+  -s|--start)
+    if ! IsNatural "${2}"; then
+      Fatal "parser: cannot start at '${2}' (not an integer >= 0)"
+    else
+      Debug "parser: --start=${2} (was ${enum_start})"
+      enum_start="${2}"
+    fi
     shift; shift
     ;;
 
-  -S|--step)
-    if ! is_positive_integer "$2"; then
-      error_msg "Cannot set enumeration step to '${2}' (not an integer >= 1)"
+  -S=*|--step=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    if ! IsPositiveInteger "${extract}"; then
+      Error "parser: cannot step by '${extract}' (not an integer >= 1)"
+    else
+      Debug "parser: --step=${extract} (was ${enum_step})"
+      enum_step="${extract}"
     fi
-    debug_msg "Setting enumeration step to ${2} (was ${enum_step})"
-    enum_step="$2"
+    shift
+    ;;
+
+  -S|--step)
+    if ! IsPositiveInteger "${2}"; then
+      Fatal "parser: cannot step by '${2}' (not an integer >= 1)"
+    else
+      Debug "parser: --step=${2} (was ${enum_step})"
+      enum_step="${2}"
+    fi
     shift; shift
     ;;
 
   -v|--verbose)
-    debug_msg "Setting verbose option to 1 (was ${verbose})"
+    Debug "parser: --verbose=1 (was ${verbose})"
     verbose=1
     shift
     ;;
 
   -V|--version)
-    version_msg
+    Version
+    ;;
+
+  -w=*|--width=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    if ! IsNatural "${extract}"; then
+      Error "parser: cannot use width of '${extract}' (not an integer >= 0)"
+    else
+      Debug "parser: --width=${extract} (was ${width})"
+      width="${extract}"
+    fi
+    shift
     ;;
 
   -w|--width)
-    if ! is_natural "$2"; then
-      error_msg "Cannot set filename width to '${2}' (not an integer >= 0)"
+    if ! IsNatural "$2"; then
+      Fatal "parser: cannot use width of '${2}' (not an integer >= 0)"
+    else
+      Debug "parser: --width=${2} (was ${width})"
+      width="${2}"
     fi
-    debug_msg "Setting filename width to ${2} (was ${width})"
-    width="$2"
     shift; shift
     ;;
 
   -x|--execute)
-    debug_msg "Setting execution to 1 (was ${execute})"
+    Debug "parser: --execute=1 (was ${execute})"
     execute=1
     shift
     ;;
 
   *)
-    debug_msg "Argument '${1}' added to positional array"
-    positional+=("$1")
+    Debug "parser: '${1}' appended to positional arguments"
+    positional+=("${1}")
     shift
     ;;
   esac
 done
 
-# main routine
-n="$enum_start"
-s="$enum_step"
+dir="$(DirectoryArgumentOrCurrent)"
+if [[ -z "${dir}" ]]; then
+  exit 1
+fi
+
+path="$(FileAbsolute "${dir}")"
+if [[ -z "${path}" ]]; then
+  exit 1
+fi
+
+Debug "resolved '${dir}' to '${path}'"
+
+#NOTE: Directory already validated, so who knows why this would fail? Just
+#      report it to the user.
+if ! cd "${path}"; then
+  Fatal "failed to enter directory '${dir}'"
+fi
+
+n="${enum_start}"
+s="${enum_step}"
 code=0
-find . -maxdepth 1 -name "$filter" -type f -printf "%f\0" \
-  | sort -z \
-  | while IFS= read -r -d '' original_fn; do
-  wide_n=$(/usr/bin/printf "%0*d\n" "$width" "$n")
-  enum_fn="${wide_n}.$(fn_extension "$original_fn")"
-  debug_msg "Widened format of '${n}' is '${wide_n}'"
-  debug_msg "Input filename is '${original_fn}'"
-  debug_msg "Output filename is '${enum_fn}'"
+
+while IFS= read -r -d '' original_fn; do
+  wide_n=$(/usr/bin/printf -- '%0*d\n' "${width}" "${n}")
+  enum_fn="${wide_n}.$(FileExtension "$original_fn")"
+
   if [[ "$execute" -eq 1 ]]; then
-    if ! mv "$original_fn" "${enum_fn}"; then
+    if ! mv "${original_fn}" "${enum_fn}"; then
       code=1
     fi
-  else
-    /usr/bin/printf "#mv %s %s\n" "$original_fn" "$enum_fn"
-  fi
-  n=$((n+s))
-done
 
-# return stored code
-exit "$code"
+  else
+    /usr/bin/printf -- '#mv %s %s\n' "${original_fn}" "${enum_fn}"
+
+  fi
+
+  n=$((n+s))
+
+done < <(find . -maxdepth 1 -name "${filter}" -type f -printf "%f\0" | sort -z)
+
+exit "${code}"
 
diff --git a/core/rand b/core/rand
--- a/core/rand
+++ b/core/rand
@@ -4,95 +4,115 @@ name="rand"
 version="1.0"
 read -r -d '' help_message <<-EOF
 	Get a random number within an inclusive range
-	Usage: rand [OPTIONS] START END
+	Usage: rand [OPTIONS] START STOP
 	Options:
 	 -h, --help        print this message and exit
-	 -n N, --number N  print N numbers (Default: 1)
+	 -n=N, --number=N  print N numbers (Default: 1)
 	 -q, --quiet       suppress error messages and prompts
 	 -v, --verbose     show additional messages
 	 -V, --version     print version number and exit
-	 -w N, --width N   print numbers zero-padded to N-wide (Default: 0)
+	 -w=N, --width=N   print numbers zero-padded to N-wide (Default: 0)
 EOF
 
-source /usr/local/lib/mylib.bash
+. /usr/local/lib/mylib.bash
 
 positional=()
 quiet=0
 verbose=0
 width=1
 number=1
-while [[ $# -gt 0 ]]; do
-  case "$1" in
+
+while [[ "$#" -gt 0 ]]; do
+  case "${1}" in
 
   -h|--help)
-    help_msg
+    Help
+    shift
+    ;;
+
+  -n=*|--number=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    if ! IsPositiveInteger "${extract}"; then
+      Error "parser: cannot set outputs to '${extract}' (not an integer >= 1)"
+    else
+      Debug "parser: --number=${extract} (was ${number})"
+      number="${extract}"
+    fi
     shift
     ;;
 
   -n|--number)
-    if ! is_positive_integer "$2"; then
-      error_msg "Cannot set number of outputs to '${2}' (not an integer >= 1)"
+    if ! IsPositiveInteger "${2}"; then
+      Error "parser: cannot set outputs to '${2}' (not an integer >= 1)"
+    else
+      Debug "parser: --number=${2} (was ${number})"
+      number="${2}"
     fi
-    debug_msg "Setting number of outputs to ${2} (was ${number})"
-    number="$2"
     shift; shift
     ;;
 
   -q|--quiet)
-    debug_msg "Setting quiet option to 1 (was ${quiet})"
+    #NOTE: Normally would emit a message with Debug, but the user is
+    #      specifically requesting that we do not.
     quiet=1
     shift
     ;;
 
   -v|--verbose)
-    debug_msg "Setting verbose option to 1 (was ${verbose})"
+    Debug "parser: --verbose=1 (was ${verbose})"
     verbose=1;
     shift
     ;;
 
   -V|--version)
-    version_msg
+    Version
+    ;;
+
+  -w=*|--width=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    if ! IsNatural "${extract}"; then
+      Error "parser: cannot use width of '${extract}' (not an integer >= 0)"
+    else
+      Debug "parser: --width=${extract} (was ${width})"
+      width="${extract}"
+    fi
+    shift
     ;;
 
   -w|--width)
-    if ! is_natural "$2"; then
-      error_msg "Cannot set zero-padding width to '${2}' (not an integer >= 0)"
+    if ! IsNatural "${2}"; then
+      Error "parser: cannot use width of '${2}' (not an integer >= 0)"
+    else
+      Debug "parser: --width=${2} (was ${width})"
+      width="${2}"
     fi
-    debug_msg "Setting zero-padding width to ${2} (was ${width})"
-    width="$2";
     shift; shift
     ;;
 
   *)
-    debug_msg "Argument '${1}' added to positional array"
-    positional+=("$1")
+    Debug "parser: '${1}' appended to positional arguments"
+    positional+=("${1}")
     shift
     ;;
   esac
 done
 
 # check arguments
-if [[ ${#positional[@]} -lt 2 ]]; then
-  debug_msg "Expected 2 arguments (given ${#positional[@]})"
-  usage_msg
-else
-  range_start="${positional[0]}"
-  range_end="${positional[1]}"
-  if ! is_integer "$range_start"; then
-    error_msg "Expected integer for range start (given '${range_start}')"
-  elif ! is_integer "$range_end"; then
-    error_msg "Expected integer for range end (given '${range_end}')"
-  elif [[ "$range_start" -ge "$range_end" ]]; then
-    error_msg "Expected ascending range (given '${range_start}' and '${range_end}')"
-  fi
+if [[ "${#positional[@]}" -lt 2 ]]; then
+  Usage
 fi
 
-# main routine
+range_start="${positional[0]}"
+range_end="${positional[1]}"
+if [[ "${range_start}" -ge "${range_end}" ]]; then
+  Fatal "cannot stop at ${range_end} (starting at ${range_start})"
+fi
+
 code=0
-if ! seq -f "%0${width}g" "$range_start" "$range_end" | shuf -n "$number"; then
+
+if ! /usr/bin/seq -f "%0${width}g" "${range_start}" "${range_end}" | shuf -n "${number}"; then
   code=1
 fi
 
-# return stored code
-exit "$code"
+exit "${code}"
 
diff --git a/core/rebom b/core/rebom
--- a/core/rebom
+++ b/core/rebom
@@ -3,41 +3,39 @@
 name="rebom"
 version="1.1"
 read -r -d '' help_message <<-EOF
-	Add BOM to a target file
-	Usage: rebom [OPTIONS] TARGET
+	Concatenate a BOM and target files
+	Usage: rebom [OPTIONS] TARGET.. > DESTINATION
 	Options:
-	 -h, --help            print this message and exit
-	 -q, --quiet           suppress error messages and prompts
-	 -v, --verbose         show additional messages
-	 -V, --version         print version number and exit
+	 -h, --help     print this message and exit
+	 -q, --quiet    suppress error messages and prompts
+	 -v, --verbose  show additional messages
+	 -V, --version  print version number and exit
 EOF
 
-source /usr/local/lib/mylib.bash
+. /usr/local/lib/mylib.bash
 . /usr/local/lib/myparse.bash
-
-# error if no filenames given
-if [[ ${#positional[@]} -eq 0 ]]; then
-  usage_msg
-fi
+RequirePositionalArguments
 
 code=0
 files=()
 for filename in "${positional[@]}"; do
-  if [ ! -f "$filename" ]; then
-    nonfatal_error_msg "No such file '$filename'"
+  if [[ ! -f "${filename}" ]]; then
+    Error "no such file '${filename}'"
     code=1
+
   else
     files+=("$filename")
+
   fi
 done
 
-# error if no valid filenames given
+# Fail early if no valid filenames given.
 if [[ ${#files[@]} -eq 0 ]]; then
   exit 1
 fi
 
-/usr/bin/printf "\xEF\xBB\xBF"
-/usr/bin/cat ${files[@]}
+/usr/bin/printf -- '\xEF\xBB\xBF'
+/usr/bin/cat "${files[@]}"
 
-exit "$code"
+exit "${code}"
 
diff --git a/core/vimsplit b/core/vimsplit
--- a/core/vimsplit
+++ b/core/vimsplit
@@ -1,58 +1,40 @@
-#!/bin/sh
+#!/bin/bash
 
 name="vimsplit"
-version="1.0"
-help_message=$(/usr/bin/cat <<-EOF
+version="1.1"
+read -r -d '' help_message <<-EOF
 	Open two files in split windows
 	Usage: vimsplit FILE1 FILE2
 	Options:
 	 -h, --help     print this message and exit
-	 -v, --version  print version number and exit
+	 -q, --quiet    suppress error messages and prompts
+	 -v, --verbose  show additional messages
+	 -V, --version  print version number and exit
 EOF
-)
 
-. /usr/local/lib/myminiparse.sh
+. /usr/local/lib/mylib.bash
+. /usr/local/lib/myparse.bash
+RequirePositionalArguments
 
-# check if right number of arguments
-if [ "$#" -eq 0 ]; then
-  (>&2 /usr/bin/printf "Usage: vimsplit FILE1 FILE2\n")
-  exit 1
-elif [ "$quiet" -eq 1 ] && [ "$#" -ne 3 ]; then
-  exit 1
-elif [ "$quiet" -ne 1 ] && [ "$#" -ne 2 ]; then
-  (>&2 /usr/bin/printf "%s: Expected 2 arguments (given $#)\n" "$name")
-  exit 1
+if [[ "${#positional[@]}" -ne 2 ]]; then
+  Fatal "expected 2 arguments (given ${#positional[@]})"
 fi
 
-# get first two files
-for arg; do
-  case "$arg" in
-  -q|--quiet)
-    #ignore these
-    ;;
-
-  *)
-    if [ -z "$file1" ]; then
-      file1="$arg"
-    elif [ -z "$file2" ]; then
-      file2="$arg"
-    fi
-    ;;
-  esac
-done
-
-# check files
-if [ ! -f "$file1" ]; then
-  if [ "$quiet" -eq 0 ]; then
-    (>&2 /usr/bin/printf "%s: No such file '%s'\n" "$name" "$file1")
-  fi
-  exit 1
-elif [ ! -f "$file2" ]; then
-  if [ "$quiet" -eq 0 ]; then
-    (>&2 /usr/bin/printf "%s: No such file '%s'\n" "$name" "$file2")
-  fi
-  exit 1
+file1="${positional[0]}"
+if [[ ! -f "${file1}" ]]; then
+  Fatal "no such file '${file1}'"
 fi
 
-/usr/bin/nvim "$file1" --cmd ":sp $file2"
+file2="${positional[1]}"
+if [[ ! -f "${file2}" ]]; then
+  Fatal "no such file '${file2}'"
+fi
+
+#NOTE: vi does not support the cmd option, so minimum default is in fact vim.
+visual="${VISUAL:=/usr/bin/vim}"
+if ! command -v "${visual}" >/dev/null 2>&1; then
+  Fatal "cannot open in visual editor program '${visual}'"
+fi
+
+exec "${visual}" "${file1}" --cmd ":sp ${file2}"
 
diff --git a/core/whiched b/core/whiched
--- a/core/whiched
+++ b/core/whiched
@@ -1,55 +1,31 @@
-#!/bin/sh
+#!/bin/bash
 
 name="whiched"
-version="1.2"
-help_message=$(/usr/bin/cat <<-EOF
+version="1.3"
+read -r -d '' help_message <<-EOF
 	Open a program with your editor
 	Usage: whiched [OPTIONS] PROGRAM
 	Options:
 	 -h, --help     print this message and exit
 	 -q, --quiet    suppress error messages
-	 -v, --version  print version number and exit
+	 -v, --verbose  show additional messages
+	 -V, --version  print version number and exit
 EOF
-)
 
-. /usr/local/lib/myminiparse.sh
+. /usr/local/lib/mylib.bash
+. /usr/local/lib/myparse.bash
+RequirePositionalArguments
 
-# NOTE: intentionally does not mirror `whichcat`/`whichhead`
-#  1. doesn't make sense to handle multiple files\
-#  2. when given no arguments, whiched should follow the lead of which NOT cat
-
-for arg; do
-  case "$arg" in
-  -q|--quiet)
-    #handled in myminiparse.sh
-    ;;
-
-  *)
-    target=$(command -v "$arg")
-    if [ -z "$target" ]; then
-      if [ "$quiet" -eq 0 ]; then
-        (>&2 /usr/bin/printf "%s: No such program '%s'\n" "$name" "$arg")
-      fi
-      exit 1
-    else
-      my_editor=${EDITOR:=/usr/bin/ed}
-      if ! command -v "$my_editor" >/dev/null 2>&1; then
-        if [ "$quiet" -eq 0 ]; then
-          (>&2 /usr/bin/printf "%s: cannot call \$EDITOR '%s', falling back to '/usr/bin/ed'\n" "$name" "$my_editor")
-        fi
-        my_editor=/usr/bin/ed
-      fi
-      $my_editor "$target"
-      exit $?
-    fi
-    ;;
-  esac
-done
-
-# if have not exited, no program was specified
-if [ "$quiet" -eq 0 ]; then
-  (>&2 /usr/bin/printf "Usage: whiched [OPTIONS] PROGRAM\n")
+target="${positional[0]}"
+abs_target="$(command -v "$target" 2>/dev/null)"
+if [[ -z "${abs_target}" ]]; then
+  Fatal "no such program '${target}'"
 fi
 
-exit 1
+editor="${EDITOR:=/usr/bin/ed}"
+if ! command -v "${editor}" >/dev/null 2>&1; then
+  Fatal "cannot open in editor program '${editor}'"
+fi
+
+exec "${editor}" "${abs_target}"
 
diff --git a/core/whichhead b/core/whichhead
--- a/core/whichhead
+++ b/core/whichhead
@@ -7,72 +7,89 @@ read -r -d '' help_message <<-EOF
 	Usage: whichhead [OPTIONS] [PROGRAM ..]
 	Options:
 	 -h, --help        print this message and exit
-	 -n N, --number N  print the first N lines (Default: 10)
+	 -n=N, --number=N  print the first N lines (Default: 10)
 	 -q, --quiet       suppress error messages
 	 -v, --verbose     show additional messages
 	 -V, --version     print version number and exit
 EOF
 
-source /usr/local/lib/mylib.bash
+. /usr/local/lib/mylib.bash
 
 positional=()
 num_lines=10
 quiet=0
 verbose=0
 
-while [[ $# -gt 0 ]]; do
-  case $1 in
+while [[ "${#}" -gt 0 ]]; do
+  case "${1}" in
 
   -h|--help)
-    help_msg
+    Help
+    shift
+    ;;
+
+  -n=*|--number=*)
+    IFS='=' read -r flag extract <<<"${1}"
+    if ! IsNatural "${extract}"; then
+      Error "parser: cannot use line count of '${extract}' (not an integer >= 0)"
+    else
+      Debug "parser: --number=${extract} (was ${num_lines})"
+      num_lines="${extract}"
+    fi
     shift
     ;;
 
   -n|--number)
-    if ! is_natural "$2"; then
-      error_msg "Cannot set number of lines to '${2}' (not an integer >= 0)"
+    if ! IsNatural "${2}"; then
+      Error "parser: cannot use line count of '${2}' (not an integer >= 0)"
+    else
+      Debug "parser: --number=${2} (was ${num_lines})"
+      num_lines="${2}"
     fi
-    debug_msg "Setting number of lines to ${2} (was ${num_lines})"
-    num_lines="$2"
     shift; shift
     ;;
 
   -q|--quiet)
-    debug_msg "Setting quiet option to 1 (was ${quiet})"
+    #NOTE: Normally would emit a message with Debug, but the user is
+    #      specifically requesting that we do not.
     quiet=1
     shift
     ;;
 
   -v|--verbose)
-    debug_msg "Setting verbose option to 1 (was ${verbose})"
+    Debug "parser: --verbose=1 (was ${verbose})"
     verbose=1
     shift
     ;;
 
   -V|--version)
-    version_msg
+    Version
     ;;
 
   *)
-    debug_msg "Argument '${1}' added to positional array"
-    positional+=("$1")
+    Debug "parser: '${1}' added to positional arguments"
+    positional+=("${1}")
     shift
     ;;
   esac
 done
 
-# main routine
+RequirePositionalArguments
+
 code=0
+
 for target in "${positional[@]}"; do
-  abs_target=$(command -v "$target")
-  if [[ -z $abs_target ]]; then
-    nonfatal_error_msg "No such program '${target}'"
+  abs_target="$(command -v "$target")"
+
+  if [[ -z "${abs_target}" ]]; then
+    Error "no such program '${target}'"
     code=1
+
   else
-    /usr/bin/head "$abs_target" -n "$num_lines"
+    /usr/bin/head "${abs_target}" -n "${num_lines}"
+
   fi
 done
 
-# return stored code
-exit "$code"
+exit "${code}"
 
diff --git a/core/whichvi b/core/whichvi
--- a/core/whichvi
+++ b/core/whichvi
@@ -1,54 +1,31 @@
-#!/bin/sh
+#!/bin/bash
 
 name="whichvi"
-version="1.2"
-help_message=$(/usr/bin/cat <<-EOF
+version="1.3"
+read -r -d '' help_message <<-EOF
 	Open a program with your visual editor
 	Usage: whichvi [OPTIONS] PROGRAM
 	Options:
 	 -h, --help     print this message and exit
 	 -q, --quiet    suppress error messages
-	 -v, --version  print version number and exit
+	 -v, --verbose  show additional messages
+	 -V, --version  print version number and exit
 EOF
-)
 
-. /usr/local/lib/myminiparse.sh
+. /usr/local/lib/mylib.bash
+. /usr/local/lib/myparse.bash
+RequirePositionalArguments
 
-# NOTE: intentionally does not mirror `whichcat`/`whichhead`
-#  1. doesn't make sense to handle multiple files\
-#  2. when given no arguments, whiched should follow the lead of which NOT cat
-
-for arg; do
-  case "$arg" in
-  -q|--quiet)
-    #handled in myminiparse.sh
-    ;;
-
-  *)
-    target=$(command -v "$arg")
-    if [ -z "$target" ]; then
-      if [ "$quiet" -eq 0 ]; then
-        (>&2 /usr/bin/printf "%s: No such program '%s'\n" "$name" "$arg")
-      fi
-      exit 1
-    else
-      my_visual=${VISUAL:=/usr/bin/vi}
-      if ! command -v "$my_visual" >/dev/null 2>&1; then
-        if [ "$quiet" -eq 0 ]; then
-          (>&2 /usr/bin/printf "%s: cannot call \$VISUAL '%s', falling back to '/usr/bin/vi'\n" "$name" "$my_visual")
-        fi
-        my_visual=/usr/bin/vi
-      fi
-      $my_visual "$target"
-      exit $?
-    fi
-    ;;
-  esac
-done
-
-if [ "$quiet" -eq 0 ]; then
-  (>&2 /usr/bin/printf "Usage: whichvi [OPTIONS] PROGRAM\n")
+target="${positional[0]}"
+abs_target="$(command -v "$target" 2>/dev/null)"
+if [[ -z "${abs_target}" ]]; then
+  Fatal "no such program '${target}'"
 fi
 
-exit 1
+visual="${VISUAL:=/usr/bin/vi}"
+if ! command -v "${visual}" >/dev/null 2>&1; then
+  Fatal "cannot open in visual editor program '${visual}'"
+fi
+
+exec "${visual}" "${abs_target}"
 
diff --git a/hardware/gpu-ls b/hardware/gpu-ls
--- a/hardware/gpu-ls
+++ b/hardware/gpu-ls
@@ -1,10 +1,28 @@
-#!/bin/sh
+#!/bin/bash
 
-header="Name:GPU:Memory
-"
-table="$(nvidia-smi --query-gpu name,utilization.gpu,utilization.memory --format=csv \
-  | sed 's/ %/%/g' \
-  | awk 'BEGIN{FS=", "; OFS=":"} {if(NR>1) print $1,$2,$3}')"
+name="gpu-ls"
+version="1.0"
+read -r -d '' help_message <<-EOF
+	List GPU devices
+	Usage: gpu-ls
+	Options:
+	 -h, --help     print this message and exit
+	 -q, --quiet    suppress error messages
+	 -v, --verbose  show additional messages
+	 -V, --version  print version number and exit
+EOF
 
-cat <<<"${header}${table}" | column --separator=":" --table
+. /usr/local/lib/mylib.bash
+. /usr/local/lib/myparse.bash
+
+csv="$(/usr/bin/nvidia-smi --query-gpu name,utilization.gpu,utilization.memory --format=csv)"
+if [[ "$?" -ne 0 ]]; then
+  Fatal "failed to query GPU"
+fi
+
+( \
+  /usr/bin/printf -- 'Name:GPU:Memory\n'; \
+  /usr/bin/sed 's/ %/%/g' <<<"${csv}" \
+    | /usr/bin/awk 'BEGIN{FS=", "; OFS=":"} {if(NR>1) print $1,$2,$3}'; \
+) | /usr/bin/column --separator=":" --table
 
diff --git a/hardware/gpu-ps b/hardware/gpu-ps
--- a/hardware/gpu-ps
+++ b/hardware/gpu-ps
@@ -1,24 +1,41 @@
 #!/bin/bash
 
-# nvidia gpu query
-query="$(nvidia-smi pmon --count=1 --select=m | sed 's/# /#/')"
-memunit="$(awk '{if(NR==2) print $4}' <<<"$query")"
+name="gpu-ps"
+version="1.0"
+read -r -d '' help_message <<-EOF
+	List GPU processes
+	Usage: gpu-ps
+	Options:
+	 -h, --help     print this message and exit
+	 -q, --quiet    suppress error messages
+	 -v, --verbose  show additional messages
+	 -V, --version  print version number and exit
+EOF
 
-# nvidia table construction
-full_header="::Memory Usage:(in ${memunit})
-PID:Process:Frame Buffer:Confidential Compute
-"
-full_table="$(awk 'BEGIN{OFS=":"} {if(NR>2) print $2,$6,$4,$5}' <<<"$query")"
+. /usr/local/lib/mylib.bash
+. /usr/local/lib/myparse.bash
 
-abbrev_header="PID:Process:Memory Usage (${memunit})
-"
-abbrev_table="$(awk 'BEGIN{OFS=":"} {if(NR>2) print $2,$6,$4}' <<<"$query")"
+pmon="$(/usr/bin/nvidia-smi pmon --count=1 --select=m)"
+if [[ "$?" -ne 0 ]]; then
+  Fatal "failed to query GPU"
+fi
 
-# switch on whether there is any confidential compute memory usage
-ccmemusage="$(awk '{if(NR>2) sum+=$5} END{print sum}' <<<"$query")"
-if [[ "$ccmemusage" -eq 0 ]]; then
-  cat <<<"${abbrev_header}${abbrev_table}" | column --separator=':' --table
+query="$(/usr/bin/sed --expression 's/# /#/' <<<"${pmon}")"
+memunit="$(/usr/bin/awk '{if(NR==2) print $4}' <<<"${query}")"
+
+# Switch on whether there is any confidential compute memory usage.
+ccmemusage="$(/usr/bin/awk '{if(NR>2) sum+=$5} END{print sum}' <<<"${query}")"
+if [[ "${ccmemusage}" -ne 0 ]] || [[ "${verbose}" -eq 1 ]]; then
+  ( \
+    /usr/bin/printf -- '::Memory Usage:(in %s)\nPID:Process:Frame Buffer:Confidential Compute\n' "${memunit}"; \
+    /usr/bin/awk 'BEGIN{OFS=":"} {if(NR>2) print $2,$6,$4,$5}' <<<"${query}"; \
+  ) | /usr/bin/column --separator=':' --table
+
 else
-  cat <<<"${full_header}${full_table}" | column --separator=':' --table
+  ( \
+    /usr/bin/printf -- 'PID:Process:Memory Usage (%s)\n' "${memunit}"; \
+    /usr/bin/awk 'BEGIN{OFS=":"} {if(NR>2) print $2,$6,$4}' <<<"${query}"; \
+  ) | /usr/bin/column --separator=':' --table
+
 fi
 
