Refactored code into multiple 'packages'. One day these may be independently installable. For now it's just an organization method.
Rewrote main README and added per-package READMEs.

Also: bug fix on whiched and whichvi. They formerly propogated an error
if $EDITOR or $VISUAL were set to a non-existant executable. Also
improved the inline documentation.

diff --git a/core/whiched b/core/whiched
--- a/core/whiched
+++ b/core/whiched
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 name="whiched"
-version="1.0"
+version="1.1"
 help_message=$(/usr/bin/cat <<-EOF
 	Open a program with your editor
 	Usage: whiched PROGRAM [OPTIONS]
@@ -14,7 +14,8 @@ EOF
 
 . /usr/local/lib/myminiparse.sh
 
-# open first non-option argument in editor, then exit
+# NOTE: intentionally does not mirror `whichcat`/`whichhead`; doesn't make
+# sense to handle multiple files
 for arg; do
   case "$arg" in
   -q|--quiet)
@@ -26,11 +27,17 @@ for arg; do
     target=$(command -v "$arg")
     if [ -z "$target" ]; then
       if [ "$quiet" -eq 0 ]; then
-        (>&2 /usr/bin/printf "%s: No such directory '%s'\n" "$name" "$target")
+        (>&2 /usr/bin/printf "%s: No such program '%s'\n" "$name" "$arg")
       fi
       exit 1
     else
       my_editor=${EDITOR:=/usr/bin/ed}
+      if ! command -v "$my_editor" >/dev/null 2>&1; then
+        if [ "$quiet" -eq 0 ]; then
+          (>&2 /usr/bin/printf "%s: cannot call \$EDITOR '%s', falling back to '/usr/bin/ed'\n" "$name" "$my_editor")
+        fi
+        my_editor=/usr/bin/ed
+      fi
       $my_editor "$target"
       exit $?
     fi
@@ -42,5 +49,5 @@ done
 if [ "$quiet" -eq 0 ]; then
   (>&2 /usr/bin/printf "Usage: whiched PROGRAM [OPTIONS]\n")
 fi
-exit 1
+exit 0
 
diff --git a/core/whichvi b/core/whichvi
--- a/core/whichvi
+++ b/core/whichvi
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 name="whichvi"
-version="1.0"
+version="1.1"
 help_message=$(/usr/bin/cat <<-EOF
 	Open a program with your visual editor
 	Usage: whichvi PROGRAM [OPTIONS]
@@ -14,7 +14,8 @@ EOF
 
 . /usr/local/lib/myminiparse.sh
 
-# open first non-option argument in editor, then exit
+# NOTE: intentionally does not mirror `whichcat`/`whichhead`; doesn't make
+# sense to handle multiple files
 for arg; do
   case "$arg" in
   -q|--quiet)
@@ -26,11 +27,17 @@ for arg; do
     target=$(command -v "$arg")
     if [ -z "$target" ]; then
       if [ "$quiet" -eq 0 ]; then
-        (>&2 /usr/bin/printf "%s: No such directory '%s'\n" "$name" "$target")
+        (>&2 /usr/bin/printf "%s: No such program '%s'\n" "$name" "$arg")
       fi
       exit 1
     else
-      my_visual=${VISUAL:=/usr/bin/ed}
+      my_visual=${VISUAL:=/usr/bin/vi}
+      if ! command -v "$my_visual" >/dev/null 2>&1; then
+        if [ "$quiet" -eq 0 ]; then
+          (>&2 /usr/bin/printf "%s: cannot call \$VISUAL '%s', falling back to '/usr/bin/vi'\n" "$name" "$my_visual")
+        fi
+        my_visual=/usr/bin/vi
+      fi
       $my_visual "$target"
       exit $?
     fi
@@ -42,5 +49,5 @@ done
 if [ "$quiet" -eq 0 ]; then
   (>&2 /usr/bin/printf "Usage: whichvi PROGRAM [OPTIONS]\n")
 fi
-exit 1
+exit 0
 
